
/**************************************************************
 *	
 *	soundShieldDown, 8 bit, 22050Hz,
 *	1 channel, 17020 bytes/channel
 *	Total Size: 1 * 17020 + 4 (header) = 17064 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundShieldDown.wav
 *	Time-stamp: Mon Dec 02 10:37:03 2013
 *	
 **************************************************************/

#ifndef __SOUNDSHIELDDOWNH__
#define __SOUNDSHIELDDOWNH__

#define SOUNDSHIELDDOWNFREQ 22050
#define SOUNDSHIELDDOWNLEN 17020

extern const unsigned char soundShieldDown[17020];

#endif /* __SOUNDSHIELDDOWNH__ */
