
/**************************************************************
 *	
 *	soundHurt, 8 bit, 22050Hz,
 *	1 channel, 4977 bytes/channel
 *	Total Size: 1 * 4977 + 4 (header) = 5021 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundHurt.wav
 *	Time-stamp: Mon Dec 02 04:50:28 2013
 *	
 **************************************************************/

#ifndef __SOUNDHURTH__
#define __SOUNDHURTH__

#define SOUNDHURTFREQ 22050
#define SOUNDHURTLEN 4977

extern const unsigned char soundHurt[4977];

#endif /* __SOUNDHURTH__ */
