
/**************************************************************
 *	
 *	soundSelect, 8 bit, 44100Hz,
 *	1 channel, 16710 bytes/channel
 *	Total Size: 1 * 16710 + 4 (header) = 16754 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundSelect.wav
 *	Time-stamp: Thu Nov 21 20:48:34 2013
 *	
 **************************************************************/

#ifndef __SOUNDSELECTH__
#define __SOUNDSELECTH__

#define SOUNDSELECTFREQ 44100
#define SOUNDSELECTLEN 16710

extern const unsigned char soundSelect[16710];

#endif /* __SOUNDSELECTH__ */
