
/**************************************************************
 *	
 *	soundAdventure, 8 bit, 44100Hz,
 *	1 channel, 8612272 bytes/channel
 *	Total Size: 1 * 8612272 + 4 (header) = 8612316 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundAdventure.wav
 *	Time-stamp: Thu Nov 21 20:33:35 2013
 *	
 **************************************************************/

#ifndef __SOUNDADVENTUREH__
#define __SOUNDADVENTUREH__

#define SOUNDADVENTUREFREQ 44100
#define SOUNDADVENTURELEN 8612272

extern const unsigned char soundAdventure[8612272];

#endif /* __SOUNDADVENTUREH__ */
