
/**************************************************************
 *	
 *	soundLose, 8 bit, 44100Hz,
 *	1 channel, 868608 bytes/channel
 *	Total Size: 1 * 868608 + 4 (header) = 868652 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundLose.wav
 *	Time-stamp: Mon Dec 02 04:31:49 2013
 *	
 **************************************************************/

#ifndef __SOUNDLOSEH__
#define __SOUNDLOSEH__

#define SOUNDLOSEFREQ 44100
#define SOUNDLOSELEN 868608

extern const unsigned char soundLose[868608];

#endif /* __SOUNDLOSEH__ */
