
/**************************************************************
 *	
 *	soundJump, 8 bit, 44100Hz,
 *	1 channel, 8850 bytes/channel
 *	Total Size: 1 * 8850 + 4 (header) = 8894 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundJump.wav
 *	Time-stamp: Thu Nov 21 20:56:17 2013
 *	
 **************************************************************/

#ifndef __SOUNDJUMPH__
#define __SOUNDJUMPH__

#define SOUNDJUMPFREQ 44100
#define SOUNDJUMPLEN 8850

extern const unsigned char soundJump[8850];

#endif /* __SOUNDJUMPH__ */
