
/**************************************************************
 *	
 *	soundVictory, 8 bit, 44100Hz,
 *	1 channel, 180864 bytes/channel
 *	Total Size: 1 * 180864 + 4 (header) = 180908 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundVictory.wav
 *	Time-stamp: Mon Dec 02 10:02:05 2013
 *	
 **************************************************************/

#ifndef __SOUNDVICTORYH__
#define __SOUNDVICTORYH__

#define SOUNDVICTORYFREQ 44100
#define SOUNDVICTORYLEN 180864

extern const unsigned char soundVictory[180864];

#endif /* __SOUNDVICTORYH__ */
