
/**************************************************************
 *	
 *	soundShieldUp, 8 bit, 22050Hz,
 *	1 channel, 22571 bytes/channel
 *	Total Size: 1 * 22571 + 4 (header) = 22615 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Jackson\Documents\NetBeansProjects\JacksonScroggs_FinalProject\soundShieldUp.wav
 *	Time-stamp: Mon Dec 02 10:37:05 2013
 *	
 **************************************************************/

#ifndef __SOUNDSHIELDUPH__
#define __SOUNDSHIELDUPH__

#define SOUNDSHIELDUPFREQ 22050
#define SOUNDSHIELDUPLEN 22571

extern const unsigned char soundShieldUp[22571];

#endif /* __SOUNDSHIELDUPH__ */
